# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tap Timer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tap Timer

  target 'Tap TimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tap TimerUITests' do
    # Pods for testing
  end

end
